# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2019 CERN.
# Copyright (C) 2019 Northwestern University.
#
# Invenio-Records-Permissions is free software; you can redistribute it
# and/or modify it under the terms of the MIT License; see LICENSE file for
# more details.

# blocklist
branches:
  except:
  - /^v\d+\.\d+(\.\d+)?(\S*)?$/

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=devel EXTRAS=all,postgresql,elasticsearch7 ES_VERSION=ES_7_LATEST

cache:
  - pip

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.26.2
  matrix:
    - REQUIREMENTS=lowest EXTRAS=all,postgresql,elasticsearch6 ES_VERSION=ES_6_LATEST
    - REQUIREMENTS=release EXTRAS=all,postgresql,elasticsearch6 ES_VERSION=ES_6_LATEST
    - REQUIREMENTS=release EXTRAS=all,postgresql,elasticsearch7 ES_VERSION=ES_7_LATEST
    - REQUIREMENTS=devel EXTRAS=all,postgresql,elasticsearch6 ES_VERSION=ES_6_LATEST
    - REQUIREMENTS=devel EXTRAS=all,postgresql,elasticsearch7 ES_VERSION=ES_7_LATEST

python:
  - "3.6"

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[${EXTRAS}]"

before_script:
  - "docker --version"
  - "docker-compose --version"

script:
  - "./run-tests.sh"

after_success:
  - coveralls
